# fly.toml app configuration file generated for taraz-backend on 2025-09-25T09:04:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taraz-backend'
primary_region = 'fra'

[build]

[env]
  NODE_ENV = "production"
  PORT = "3030"
  JWT_EXPIRES_IN = "365d"
  JWT_EXPIRES_IN_SECONDS = "3600"
  JWT_REFRESH_EXPIRES_IN = "7d"
  BCRYPT_SALT_ROUNDS = "12"
  SMTP_PORT = "587"
  CORS_ORIGIN = "https://your-frontend-domain.com"
  LOG_LEVEL = "info"

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
